# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f6c70c008033daa43082e413070c38fbad4c7ed88af6b40aa872c45f35e04e9bcf4c8f6d899ea73ff827c03db3b807f2b4a68dae896c7278275d8e117131833

test:
  secret_key_base: b89903abc67f09d5a881342485b3eaabe0e93cdfc12403a8d50cf8c811d41d568e0e8f5a5ee98e221702818872396fe0b13a85c047fa424321ca96deaba1d6a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
